name: Exemple de workflow avec echo

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build et affichage d'un message
    runs-on: ubuntu-latest
    
    steps:
      - name: Vérifier le code
        uses: actions/checkout@v2
        
      - name: Afficher un message
        run: echo "DE CIANCIO Enzo"
